#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author  : qiang.hu
# @Time: 2024/11/23


# 定义股票代码列表
stock_codes = [
    'DJI', 'GSPC', 'IXIC', 'NDX', 'QNET', 'NBI', 'NDXE', 'NQGS', 'CELS', 'NQGM', 'DIVQ', 'VOLNDX', 'SOX', 'SPX', 'CEX',
    'COR9M', 'SIXT', 'COR3M', 'BPVIX', 'DJX', 'BXMD', 'SIXV', 'SIV', 'BXMW', 'EUVIX', 'BPVIX3', 'KCJ', 'SP0BF10U', 'LOVOL',
    'BXMH', 'IBHY', 'BPVIX2', 'SP0BF10N', 'SPBFQ', 'CIV', 'SPBUF10J', 'BXMU', 'SIXE', 'ESGST', 'EUVIX2', 'SP0BF10D', 'BXLVH',
    'COR1M', 'PUTD', 'SPEN10', 'BXDE', 'DDB', 'DJS', 'PUTY', 'BFLY', 'PUT', 'EUVIX3', 'SP0BF10L', 'DDSEV', 'BPVIX1', 'SP2BF10G',
    'DDLEV', 'CMBO', 'MLPMP', 'SPENME10', 'BXLKH', 'DSVIER', 'JYVIX1', 'CDSPT', 'SPENME03', 'DXL', 'SIXRE', 'SP0BF10Y', 'TYVIX1',
    'BXLFH', 'BXESG', 'SMLC', 'SPEN07', 'SIXM', 'SPRO03', 'SPBNQ', 'COR1Y', 'MHDP', 'SISM', 'BXD', 'BXMC', 'SISIN', 'CLL1M',
    'SP0BF10G', 'BXY', 'SISB', 'SIXB', 'VXHYG', 'CLL', 'LONGVOL', 'SIXU', 'SPRF10', 'SPDVXT', 'SP0BF10F', 'SPRS10', 'SPBUF10F',
    'SP2BF10D', 'VPN', 'TYVIX3', 'SPEN', 'NANOS', 'SPROME02', 'SNVIVBT', 'SPROME03', 'SPROME11', 'GVX', 'DSVIX', 'SP7BF10G',
    'SPRF03', 'SPRF02', 'CLLZ', 'SPRF01', 'SP0BF10M', 'VIX52W', 'CDSPG', 'SPEN05', 'SP7BF10Y', 'COR90D', 'SP0BF10S', 'SP7BF10J',
    'SPBUF10U', 'VIX1D', 'OEX', 'VIX3M', 'VAFF8', 'IBIG', 'TWLV1', 'SPBUF10A', 'SMLCW', 'SPVXET', 'SIXI', 'CNDR', 'SP7BF10M',
    'SP7BF10O', 'VIF', 'VXIND1', 'SP2BF10Y', 'SPENME', 'SPROME', 'SPRS07', 'SPENME07', 'VW2VX', 'JYVIX', 'COR30D', 'VINXE',
    'PPUT3M', 'SP2BF10F', 'SRO', 'JYVIX3', 'SPBUF10O', 'VXFWA', 'VIXNOV', 'SISR', 'VX3MB', 'SP0BF10A', 'VX3MN', 'SPBUF10G',
    'SPEN03', 'VXFXI', 'SPRO07', 'SRVIX', 'SHORTVOL', 'TYVIX', 'SP2BF10S', 'SP0BF10J', 'SPENME02', 'XSPAM', 'VXDEC', 'SIXC',
    'SPRO04', 'EUVIX1', 'SPJGBV', 'VWA', 'MSV', 'VIXFEB', 'VXW3', 'VIX44W', 'SP7BF10F', 'VXW4', 'SPRO10', 'SIXY', 'SP2BF10M',
    'VIN', 'SISV', 'VIX49W', 'TWAV3', 'SISRE', 'CLL3M', 'SPRI', 'VIXJUN', 'PUTVM', 'SPATI', 'VIXDEC', 'SPEN02', 'SVRPO',
    'SPRO02', 'SPRO09', 'VIXMAY', 'COR6M', 'VIX45W', 'SP2BF10O', 'VXSEP', 'SPDVXE', 'SPRO', 'VXIND2', 'SPBUF10M', 'SIST',
    'TWBV2', 'VXXLE', 'SP7BF10L', 'SPROME07', 'SPRF11', 'SP2BF10U', 'VIXAPR', 'VAF', 'TWLV3', 'VXIEF', 'TYVIX2', 'VIXJUL',
    'DLVIX', 'SISUT', 'VIXJAN', 'VRO', 'WPUT', 'VIX48W', 'TWLV6', 'VIXMAR', 'SPRF05', 'SPEN08', 'VXD', 'VXST', 'VIX43W',
    'UZN', 'SPRF12', 'VAFM8', 'SPROME01', 'SPRO08', 'SPEN04', 'VIX41W', 'SP7BF10D', 'SPENME01', 'TWLV5', 'SPJGBVRT', 'VX3MA',
    'VINMO', 'VW1VX', 'VXB', 'SPRF08', 'PWT', 'BXMVM', 'SPENME11', 'VIX9D', 'SPRS04', 'VAFZ7', 'JYVIX2', 'SPRF07', 'VXTA3',
    'SPEN12', 'SP2BF10N', 'SPRO01', 'SP7BF10N', 'SPRO06', 'VW3VX', 'SPBUF10D', 'SP7BF10S', 'SPVXEP', 'VXFWB', 'SPENME06',
    'VXIND3', 'BXM', 'VXTB2', 'SMILE', 'VXW6', 'SPESG', 'VXSLV', 'SPRF', 'TWLV9', 'VFTW2', 'SPROME09', 'COR10D', 'SPRO05',
    'SNVIVBN', 'VSTF', 'SISC', 'VXW5', 'VXMAR', 'SPBUF10S', 'MLPEN', 'VXTH', 'VXTA2', 'COR70D', 'VXMT', 'VIO', 'VXS', 'DVS',
    'SPRF09', 'SPRF06', 'VAFZ8', 'MLPMH', 'SPBUF10N', 'VXTB3', 'DDA', 'SPENME05', 'VPD', 'TWAV1', 'VXTB1', 'SPROME12', 'VIX40W',
    'XSP', 'SPBUF10L', 'SPENME09', 'XEO', 'SP2BF10L', 'OET', 'VAEEM', 'WIV', 'SPEN06', 'VXTA1', 'VIXSEP', 'SKEW', 'VXVOL', 'OIV',
    'VSTG', 'SP7BF10A', 'RXM', 'SP2BF10J', 'SET', 'VXTYS', 'VBEEM', 'SPEN09', 'SP2BF10A', 'VWB', 'SIXR', 'SPROME06', 'TWAV2',
    'VAFH8', 'VVIX', 'VSTN', 'VIX47W', 'SP0BF10O', 'SPRO12', 'VSEWZ', 'VIX1Y', 'SPBUF10Y', 'VIX50W', 'VXJUN', 'TWBV1', 'VSTRP',
    'SPROME04', 'VIFMO', 'PPUT', 'TWLV8', 'TWLV7', 'VX3MF', 'SP7BF10U', 'VFTW1', 'VAFZ9', 'SPENME12', 'VAFV7', 'SPRF04', 'TWLV4',
    'VXGDX', 'SPTST', 'VAFM9', 'TWLV2', 'TWBV3', 'SPRO11', 'VXO', 'SISY', 'CALD', 'VIXMO', 'SISE', 'VAFX7', 'XSR', 'SPROME05',
    'SPEN01', 'VIXOCT', 'VIX6M', 'SPENME04', 'SPROME10', 'MHDT', 'SSTGK', 'SPROME08', 'SPENME08', 'CDSPV', 'RON', 'SPEN11',
    'SPRS01', 'SPAI'
]

# 将列表转换为集合
stock_codes_set = tuple(stock_codes)

# 打印集合
print(stock_codes_set)